-- Create the table for storing news articles
create table public.articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null unique,
  headline text not null,
  source text,
  author text,
  page_number integer,
  page integer,
  category text,
  companies text[], -- Array of strings for company names
  published_at timestamp with time zone,
  publish_date timestamp with time zone,
  
  -- Add constraints or indexes if needed
  constraint articles_url_key unique (url)
);

-- Enable Row Level Security (RLS)
alter table public.articles enable row level security;

-- Create a policy that allows anyone to read articles (public access)
-- Adjust this if you want only authenticated users to read
create policy "Allow public read access"
  on public.articles
  for select
  using (true);

-- Create a policy that allows only authenticated users (service_role or authenticated) to insert/update
-- For the scraper, you will likely use the SERVICE_ROLE_KEY to bypass RLS, 
-- or create a specific policy for a scraper user.
-- This policy allows full access to authenticated users (like your scraper if it signs in, or uses the secret key)
create policy "Allow authenticated insert/update"
  on public.articles
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
